import { UserRole } from '@prisma/client'; // Assuming UserRole enum is generated by Prisma

export interface AuthUser {
  id: string;
  email: string;
  role: UserRole;
  name?: string;
}

declare global {
  namespace Express {
    export interface Request {
      user?: AuthUser;
    }
  }
}
